//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JunkCar.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_Offer
    {
        public Sal_Offer()
        {
            this.Sal_Customer_Offer = new HashSet<Sal_Customer_Offer>();
        }
    
        public int Offer_Id { get; set; }
        public Nullable<int> Model_Year_Id { get; set; }
        public Nullable<int> Zip_Id { get; set; }
        public Nullable<int> Questionnaire_Id { get; set; }
        public Nullable<int> Questionnaire_Result_Id { get; set; }
        public int Offer_Price { get; set; }
        public bool Is_Negotiable { get; set; }
        public string Remarks { get; set; }
        public byte Is_Active { get; set; }
        public System.DateTime Created_Date { get; set; }
        public int Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<long> Audit_Id { get; set; }
        public string User_IP { get; set; }
        public int Site_Id { get; set; }
        public Nullable<short> No_Of_Cylinder { get; set; }
    
        public virtual ICollection<Sal_Customer_Offer> Sal_Customer_Offer { get; set; }
        public virtual Set_Questionnaire Set_Questionnaire { get; set; }
        public virtual Set_Questionnaire_Result Set_Questionnaire_Result { get; set; }
    }
}
