//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JunkCar.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_Customer
    {
        public Sal_Customer()
        {
            this.Sal_Customer_Contact = new HashSet<Sal_Customer_Contact>();
            this.Sal_Customer_Offer = new HashSet<Sal_Customer_Offer>();
        }
    
        public int Customer_Id { get; set; }
        public string Customer_Code { get; set; }
        public string Customer_Name { get; set; }
        public Nullable<int> Assigned_User_Code { get; set; }
        public Nullable<int> Currency_Id { get; set; }
        public byte Is_Active { get; set; }
        public System.DateTime Created_Date { get; set; }
        public int Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<long> Audit_Id { get; set; }
        public string User_IP { get; set; }
        public int Site_Id { get; set; }
    
        public virtual ICollection<Sal_Customer_Contact> Sal_Customer_Contact { get; set; }
        public virtual ICollection<Sal_Customer_Offer> Sal_Customer_Offer { get; set; }
        public virtual Sec_User Sec_User { get; set; }
    }
}
