//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JunkCar.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_Customer_Contact
    {
        public int Customer_Contact_Id { get; set; }
        public int Customer_Id { get; set; }
        public int Contact_Type_Id { get; set; }
        public Nullable<bool> Is_Default { get; set; }
        public string Customer_Contact { get; set; }
        public Nullable<int> City_Id { get; set; }
        public Nullable<int> County_Id { get; set; }
        public Nullable<int> State_Id { get; set; }
        public Nullable<int> Country_Id { get; set; }
        public string Zip_Code { get; set; }
        public short Sort_Order { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public byte Is_Active { get; set; }
        public string User_IP { get; set; }
        public Nullable<long> Audit_Id { get; set; }
        public int Site_Id { get; set; }
    
        public virtual Sal_Customer Sal_Customer { get; set; }
        public virtual Set_City Set_City { get; set; }
        public virtual Set_Contact_Type Set_Contact_Type { get; set; }
        public virtual Set_Country Set_Country { get; set; }
        public virtual Set_State Set_State { get; set; }
    }
}
