//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JunkCar.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_Customer_Vehicle
    {
        public Sal_Customer_Vehicle()
        {
            this.Sal_Customer_Vehicle_Doc = new HashSet<Sal_Customer_Vehicle_Doc>();
        }
    
        public int Customer_Vehicle_Id { get; set; }
        public int Customer_Offer_Id { get; set; }
        public string Registration_No { get; set; }
        public Nullable<int> Registration_Year { get; set; }
        public Nullable<int> Manufacturing_Year { get; set; }
        public string Insurance_No { get; set; }
        public string Inspection_No { get; set; }
        public string Image_Path { get; set; }
        public Nullable<int> Image_Count { get; set; }
        public string Remarks { get; set; }
        public byte Is_Active { get; set; }
        public System.DateTime Created_Date { get; set; }
        public int Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<long> Audit_Id { get; set; }
        public string User_IP { get; set; }
        public int Site_Id { get; set; }
    
        public virtual Sal_Customer_Offer Sal_Customer_Offer { get; set; }
        public virtual ICollection<Sal_Customer_Vehicle_Doc> Sal_Customer_Vehicle_Doc { get; set; }
    }
}
