//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JunkCar.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sec_User_Contact
    {
        public int User_Contact_Id { get; set; }
        public int User_Code { get; set; }
        public int Contact_Type_Id { get; set; }
        public Nullable<bool> Is_Default { get; set; }
        public string User_Contact { get; set; }
        public Nullable<int> City_Id { get; set; }
        public Nullable<int> State_Id { get; set; }
        public Nullable<int> Country_Id { get; set; }
        public string Zip_Code { get; set; }
        public short Sort_Order { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public byte Is_Active { get; set; }
        public string User_IP { get; set; }
        public Nullable<long> Audit_Id { get; set; }
        public int Site_Id { get; set; }
    
        public virtual Sec_User Sec_User { get; set; }
    }
}
