//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JunkCar.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Set_Make
    {
        public Set_Make()
        {
            this.Sal_Customer_Offer = new HashSet<Sal_Customer_Offer>();
            this.Set_Model = new HashSet<Set_Model>();
            this.Set_Model_Year = new HashSet<Set_Model_Year>();
        }
    
        public int Make_Id { get; set; }
        public string Make_Name { get; set; }
        public short Sort_Order { get; set; }
        public byte Is_Active { get; set; }
        public System.DateTime Created_Date { get; set; }
        public int Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<long> Audit_Id { get; set; }
        public string User_IP { get; set; }
        public int Site_Id { get; set; }
    
        public virtual ICollection<Sal_Customer_Offer> Sal_Customer_Offer { get; set; }
        public virtual ICollection<Set_Model> Set_Model { get; set; }
        public virtual ICollection<Set_Model_Year> Set_Model_Year { get; set; }
    }
}
