//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JunkCar.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Set_Site
    {
        public Set_Site()
        {
            this.Set_Site_Contact = new HashSet<Set_Site_Contact>();
        }
    
        public int Site_Id { get; set; }
        public string Site_Name { get; set; }
        public short Sort_Order { get; set; }
        public byte Is_Active { get; set; }
        public System.DateTime Created_Date { get; set; }
        public int Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<long> Audit_Id { get; set; }
        public string User_IP { get; set; }
    
        public virtual ICollection<Set_Site_Contact> Set_Site_Contact { get; set; }
    }
}
