//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JunkCar.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Set_Audit_Log
    {
        public long Audit_Id { get; set; }
        public int Primary_Key { get; set; }
        public Nullable<long> Previous_Audit_Id { get; set; }
        public string Action_Type { get; set; }
        public System.DateTime Log_Date { get; set; }
        public string Action_Component { get; set; }
        public string Old_Record_XML { get; set; }
        public string New_Record_XML { get; set; }
        public int User_Code { get; set; }
        public string User_IP { get; set; }
        public byte Is_Active { get; set; }
        public int Site_Id { get; set; }
    }
}
