//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JunkCar.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Set_City
    {
        public Set_City()
        {
            this.Sal_Customer_Contact = new HashSet<Sal_Customer_Contact>();
            this.Set_Zip_Code = new HashSet<Set_Zip_Code>();
        }
    
        public int City_Id { get; set; }
        public string City_Code { get; set; }
        public string City_Name { get; set; }
        public int County_Id { get; set; }
        public int State_Id { get; set; }
        public int Country_Id { get; set; }
        public byte Is_Active { get; set; }
        public System.DateTime Created_Date { get; set; }
        public int Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<long> Audit_Id { get; set; }
        public string User_IP { get; set; }
        public int Site_Id { get; set; }
    
        public virtual ICollection<Sal_Customer_Contact> Sal_Customer_Contact { get; set; }
        public virtual Set_Country Set_Country { get; set; }
        public virtual Set_County Set_County { get; set; }
        public virtual Set_State Set_State { get; set; }
        public virtual ICollection<Set_Zip_Code> Set_Zip_Code { get; set; }
    }
}
